### ISSUE TITLE
Doesn't work on ScriptableObjects

### ISSUE THREAD

**Issue by tomascinga** [madsbangh/EasyButtons#1]
Button doesn't appear for scriptable objects, which is quite useful.

One solution is to duplicate the editor code, and change the editor type to ScriptableObject as such:
`[CustomEditor(typeof(ScriptableObject), true)]`
or change the original editor type to `Object`, which will work for both scriptable objects and monobehaviours. I'm just not sure about any other implications it can cause.

**Comment by madsbangh** [comment]
Good point. I hadn't thought so far. This is definitely worth looking into :)

**Comment by madsbangh** [comment]
I tried both solutions and both seem to work. I went with the more simple 'Object' method. It seems to work well with no implications.

Thanks for your contribution!
