### ISSUE TITLE
Make EasyButtons a package manager package

### ISSUE THREAD

**Issue by madsbangh** [madsbangh/EasyButtons#13]
[Unity Docs for custom packages](https://docs.unity3d.com/Manual/CustomPackages.html)

**Comment by rfadeev** [comment]
Hi, I can work on this, but first would like to know repository structure you want to have. Options include single `master` branch which is package itself or two branches `master` and `upm` with `master` branch being Unity project and `upm` branch being package only.

Example of single branch branch: https://github.com/Unity-Harry/Unity-AssetDependencyGraph
Example of two branches: https://github.com/mob-sakai/UpmGitExtension

**Comment by madsbangh** [comment]
Thank you so much! That would be really appreciated.

I have to admit I don't know enough about UPM to make that decision. What would you recommend?
As far as I understand, having a separate branch will work fine as long as it is appended to the url when adding it to a project's dependencies.
I am however tempted to keep it simple and just use one branch, if the structure of the repository changes too drastically.

Are there any other pros and cons we should consider?

And again, thank you for your contributions :)

**Comment by rfadeev** [comment]
Currently repository is a Unity project hence structure would change indeed if use single branch support. While single branch looks more simple, from another perspective package development can become more complicated as you should have Unity project somewhere else with package repository cloned somewhere under `Assets` folder.

So both approaches have pros and cons. For my repositories I used single branch and bumped into issue with samples (see [post](https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/#post-4986755) on Unity forum) so now I'm also considering using two branches strategy (but did not try yet). For two branches strategy ideally need to automate push to package branch. Maybe for this project it's not critical as it's not actively developing.

**Comment by madsbangh** [comment]
If 2 branches could be a fun exercise for you, then I'd say go for it :) the repo is quite small, so I think it would be a perfect testbed - especially considering how rare updates are

**Comment by rfadeev** [comment]
One more thing before starting 2 branches approach. I assume github allows pull request to single branch only. In that case new branch should be created in the repository first to I can submit pull request to it (actually it will be two pull requests - `master` branch first and package branch later).

**Comment by madsbangh** [comment]
Sure thing :) let me know when to create the upm branch

**Comment by madsbangh** [comment]
I have created the branch 13-unity-package-manager-support based on current master. I hope this is what you need :) otherwise let me know.

**Comment by madsbangh** [comment]
Accidentally hit "Close and comment" instead of "Comment" 🥇

**Comment by rfadeev** [comment]
No worries.

I've already created `13-unity-package-manager-support` (see https://github.com/rfadeev/EasyButtons/commits/13-unity-package-manager-support) and plan is following:
1. Once `13-unity-package-manager-support` is ready, open pull request to master
2. Once pull request is merged, open next one targeting `upm` branch. At that moment content of `upm` branch should be generated automatically / semi-automatically. I'm thinking over how to do that at the moment.
