### ISSUE TITLE
Mode button modes

### ISSUE THREAD

**Issue by rhys-vdw** [madsbangh/EasyButtons#20]
Hey, love this library. I have a case where I need a button this is _only_ enabled in play mode (because it starts an animation sequence for testing).

Maybe a `ButtonMode.EnabledInPlayModeOnly`?

Feel free to close this if it seems too niche, I can see this is probably a rare case and might start eroding the "easy" in EasyButtons.

**Comment by rhys-vdw** [comment]
I just realized that this is already supported, apologies. Very silly of me.

**Comment by madsbangh** [comment]
No problem :D Thanks for the kind words!
I agree, it is a good idea haha
