### ISSUE TITLE
EasyButtons Not Working In 2021.3.17f.

### ISSUE THREAD

**Issue by Zenodeon** [madsbangh/EasyButtons#26]
EasyButtons is not working in 2021.3.17f, no errors or anything.

**Comment by madsbangh** [comment]
Thank you for letting me know! I will have a look :)

**Comment by Zenodeon** [comment]
Currently, I am using 2021.3.21f and having the same issues over there too.

**Comment by Zenodeon** [comment]
Is it possible to make it work by keeping the Folder in a different folder inside the asset folder?

**Comment by madsbangh** [comment]
Thanks for the repro @Zenodeon and thank you for testing it in 2021.3.21f1 as well! 😄 That is good to know.

On your reproduction case: I tried both of the following in 2021.3.18f1 and it still worked for me in either case.
(current master branch)
- Moved EasyButtons into another folder.
- Moved EasyButtons into the Plugins folder.

One thing that comes to mind is EasyButton's compatibility with other plugins that change or improve the inspector in some way.
Do you happen to have any other plugins in the project?

**Comment by Zenodeon** [comment]
> On your reproduction case: I tried both of the following in 2021.3.18f1 and it still worked for me in either case.
(current master branch)

Did you close Unity and Open it again? 
When I kept the plugin folder in the asset folder and moved it to a folder, it was still working but after restarting unity, it was gone.

I use Naughty Attributes mainly and I think it was present in that project, will test it in a new Project and let you know.

I dont want to use openupm as I am exporting them to .unitypackage (Utility Package used in our workflow) to give them to my co-workers, so they can choose if they want this to be imported to their project or not.

**Comment by Zenodeon** [comment]
Ok, I tackled down Naughty Attributes fault and not this plugin's fault.

Bro is creating CustomEditor For UnityEngine.Object 💀, and handling the Inspector Drawing stuff there, will take the issue to them. 

Thanks for the Support.
