### ISSUE TITLE
Button does not seem to fire function for instances of a class?

### ISSUE THREAD

**Issue by Shadestyle** [madsbangh/EasyButtons#36]
When adding a button and then adding a component which uses the button, pressing the button does not seem to fire the function on the component.  When using it to instantiate objects in editor, it appears to not actually retrieve the transform of the object it is being fired on.

**Comment by Shadestyle** [comment]
Apologies, issue is solved.

**Comment by madsbangh** [comment]
No worries :) thank you for following up and closing the issue <3
