### ISSUE TITLE
Not actually an issue

### ISSUE THREAD

**Issue by skylorbeck** [madsbangh/EasyButtons#38]
Hello! Just wanted to say thank you for this package. I was blown away at how it just worked immediately after importing without needing to change anything or do any setup. I have always wanted buttons in the inspector but never wanted to figure out how to make it myself. 

Hats off to you! Thank you!

**Comment by madsbangh** [comment]
Hah! Thank you <3 That made my day!

At this point, I think most of the credit should go to all the contributors that have made this package more accessible and useful!
