### ISSUE TITLE
Custom editor must inherit ObjectEditor for button attribute to work

### ISSUE THREAD

**Issue by rfadeev** [madsbangh/EasyButtons#4]
If there is custom editor for the class which uses `Button` attribute, buttons won't be drawn if this custom editor is inherited from `Editor`. So this code wont's show any buttons in the inspector

```
[CustomEditor(typeof(ButtonsExample))]
public class ButtonsExampleEditor : Editor
{
    public override void OnInspectorGUI()
    {
        base.OnInspectorGUI();
        // Other custom editor code
    }
 }
```

Changing to inheriting `ObjectEditor` helps

```
[CustomEditor(typeof(ButtonsExample))]
public class ButtonsExampleEditor : ObjectEditor
{
    public override void OnInspectorGUI()
    {
        base.OnInspectorGUI();
        // Other custom editor code
    }
 }
```

But this means for any script which uses `Button` attribute, custom editor inheritance should be changed (which can be undesired and sometimes not possible). I tried to tackle the problem with `PropertyDrawer` and `DecoratorDrawer` but they work only on fields, so no idea for how to solve this. Maybe it's worth mentioning in readme.

**Comment by madsbangh** [comment]
Ah yes! Nicely spotted.
Yes, this is a tricky one :/ I will let the issue stay open in hopes that someone has a fix.
Until that I will add a comment to the readme as you suggest :)
