### ISSUE TITLE
Space between buttons

### ISSUE THREAD

**Issue by sleepandpancakes** [madsbangh/EasyButtons#8]
Thanks for the awesome attribute, it's a total Unity lifesaver. Is there a way to easily add spaces between buttons (like how `[Space]` will add empty space to an inspector when placed before a field)?

**Comment by madsbangh** [comment]
Thanks! Much appreciated :) That would indeed be a cool feature, but EasyButtons has no way of doing it right now. I will keep this issue open for anyone who wants to tackle this problem.

Right now I see two ways this could be done:
* One is to make EasyButtons aware of attributes like HeaderAttribute and SpaceAttribute, but still draw all the buttons in their own section like they currently are.
* The other option would be to try and draw them the same way as fields are drawn by Unity, intermingled between the rest of the inspector fields. This might be quite a bit more advanced if I had to guess.

**Comment by trulyspinach** [comment]
I have opened a pull request to support this feature.
In order to keep this little program simple, I chose to implement it with one additional parameters and a fixed length of spacing.
 
Hope this would help :)

**Comment by madsbangh** [comment]
Closed by #9
